Create a function that will 
1. multiply its parameters, print and return the result.
2. ask the user to input 2 numbers, multiply and print the result.

In [56]:
def mult(x, y):
    if not isinstance(x, (int, float)):
        raise ValueError("Invalid argument.") 
    
    if not isinstance(y, (int, float)):
        raise ValueError("Invalid argument.") 
    
    res = x * y
    print(res)

    return res

def input_number(msg):

    while True:
        try:
            return int(input(msg))
        except ValueError as verr:
            print("Invalid number.", verr)


# mult(3.0, 5)

n1 = input_number("Please enter the first number: ")
n2 = input_number("Please enter the second number: ")
mult(n1, n2)

30


30

Write a function that prints a parameter n times. (with a pause of m milliseconds)

In [7]:
import time

def repeat(c="*", n=5):
    for _ in range(n):
        print(c)
        time.sleep(1)  # Sleep for 1 sec

repeat()

*
*
*
*
*


Write a function, that takes an integer and returns True if the number is odd.

In [8]:
def is_odd(n):
    return n % 2 == 1

print(is_odd(1))
print(is_odd(2))

True
False


Write a compare function that returns 1 if the first parameter is greater than the second, and -1 otherwise.

In [9]:
def compare(x, y):
    return 1 if x > y else -1

r1 = compare(1, 2)
r2 = compare(2, 1)

print(r1)
print(r2)

-1
1


Write a recursive program to sum first n natural numbers.

In [10]:
def sum_recursive(n):
    if n <= 0:
        return 0
    if n == 1:
        return 1
    
    return n + sum_recursive(n-1)


sum_recursive(6)

21

Write a program that accepts a full name, and return initials.

In [11]:
def initials(fullname: str) -> str:
    res = ""
    names = fullname.split()              # a list of names
    first_letters = [n[0] for n in names] # transform the list of names into list of first letters
    return "".join(first_letters)         # join - from list to string

print(initials("Jose Alfonso Garcia"))

JAG


Write a program that counts the number of times the given letter appears in a given string:

In [12]:
def letter_counter(c:str, w: str) -> int:
    return w.lower().count(c.lower())

cnt = letter_counter("A", "MaSAl")

print(cnt)

2


Count each letter in a given string.

In [13]:
def summary(w: str):
    letters = {}
    for c in w.lower():
        try:
            letters[c] += 1
        except KeyError:
            letters[c] = 1
    
    print(letters)

summary("Attribute")


{'a': 1, 't': 3, 'r': 1, 'i': 1, 'b': 1, 'u': 1, 'e': 1}


Ask the user to type in their name and then tell them how many vowels are in their name.

In [14]:
def vowel_counter():
    cnt = 0
    vowels = ["a", "e", "i", "o", "u", "A", "E", "I", "O", "U"]

    name = input("Please enter your name: ")

    for c in name:
        if c in vowels:
            cnt += 1

    return cnt

vowel_counter()

0

Write a function called drawRectangle. This function should take two parameters, width and height, and print a rectangle made of # characters with the specified dimensions.

In [15]:
def drawRectangle(w, h):
    for i in range(h):
        for j in range(w):
            print("#",end="")
        
        print("")

drawRectangle(5, 3)

#####
#####
#####


Print the the multiplication table

In [16]:
for i in range(1, 10):
    print(f"*** {i} ***")
    for j in range(1, 10):
        print(f"{i} * {j} =", i*j)

*** 1 ***
1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
*** 2 ***
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
*** 3 ***
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
*** 4 ***
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
*** 5 ***
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
*** 6 ***
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
*** 7 ***
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
*** 8 ***
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
*** 9 ***
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81


Create a list with the names of friends. Calculate the average length of the names.

Create a list with the names of friends and colleagues. Search for the name John. Print not found if you didn't find it.

In [17]:
friends = ["Alice", "BoB", "Charlie", "Isabella"]

q = "bob"
friends_lower = [n.lower() for n in friends]
if q.lower() in friends_lower:
    print(f"Found: {q}")
else:
    print(f"Not Found: {q}")

Found: bob


In [18]:
friends  = ["Alice", "Bob", "Charlie", "Isabella"]

lengths = [len(f) for f in friends]

print(sum(lengths)/len(lengths))

5.75


Create a simple collection of n scores. 
1. Access and modify the last element.
2. Add a score to the list.
3. Calculate the max, min and average of all the scores.
4. Count the number of fails (pass score: 60)
5. Count the number of 100s.
6. Calculate a list of letter grades from the scores.
7. Return a new list that contains all but the first and last elements. ie, middle([1,2,3,4]) should return [2,3]

In [21]:
scores = [70, 60, 40, 80, 90]

scores[-1] = 100
scores.append(50)

print(max(scores))
print(min(scores))
print(sum(scores)/len(scores))

fails = [s for s in scores if s<60]
print(len(fails))

print(scores.count(100))

print(scores[1:-1])

100
40
66.66666666666667
2
1
[60, 40, 80, 100]


Write a function that takes a list and returns True if there is any element that appears more than once.

In [20]:
def has_duplicates_v1(l: list) -> bool:

    freq = {}
    for item in l:
        try:
            freq[item] += 1
        except KeyError:
            freq[item] = 1

    for k in freq:
        if freq[k] > 1:
            return True
    
    return False

def has_duplicates_v2(l: list) -> bool:
    """By converting the list to a set, eliminate duplicates, and then 
    comparing the lengths of the original list and the set effectively determines if there are duplicates."""

    uniques = set(l)
    return len(uniques) < len(l)

q  = [1, 2, 3, 4]

print(has_duplicates_v1(q))
print(has_duplicates_v2(q))

False
False


Given two strings, return true if the second is an anagram of the first.
An anagram is a word or phrase formed by rearranging the letters of a different word or phrase, using all the original letters exactly once.
* "Santa" = "Satan"
* "silent" = "listen"
* "Madam Curie" = "Radium came"
* "Tom Marvolo Riddle" = "I am Lord Voldemort"

In [30]:


def anagram(s1, s2):
    freq1 = {}
    for c in s1:
        try:
            freq1[c] += 1
        except KeyError:
            freq1[c] = 1
    # remove white spaces
    try: 
        del freq1[" "]
    except KeyError:
        pass

    freq2 = {}
    for c in s2:
        try:
            freq2[c] += 1
        except KeyError:
            freq2[c] = 1
            
    # remove white spaces
    try:
        del freq2[" "]
    except KeyError:
        pass

    print(freq1)
    print(freq2)

    return freq1 == freq2


arg0 = "li sten"
arg1 = "silent"
anagram(arg0, arg1)

{'l': 1, 'i': 1, 's': 1, 't': 1, 'e': 1, 'n': 1}
{'s': 1, 'i': 1, 'l': 1, 'e': 1, 'n': 1, 't': 1}


True

Write a program that converts temperatures between Celsius and Fahrenheit. 
f = (c * 9/5) + 32

In [32]:
def celcius_to_fahrenheit(c):
    return c * 1.8 + 32


celcius_to_fahrenheit(1)

33.8

Write a number-guessing game. 
Generate a random number between 1 and 100. Ask the user to guess the number. Give feedback on whether the guess is too high or too low.

In [37]:
import random

def get_int():

    guess = -1
    invalid = True
    while invalid:
        # Ask the user to guess the number
        try:
            guess = int(input("Guess the number: "))
            break
        except ValueError:
            print("Invalid input. Please enter a number.")

    return guess

def game():

    # Generate a random number between 1-100
    secret = random.randint(1, 100)

    print("Pisst, the secret number is", secret)

    gameover = False
    while not gameover:
        # Ask the user to guess the number
        guess = get_int()

        # Evaluate the answer and give feedback
        if guess < secret:
            print("Too low. Try Again.")
        elif guess > secret:
            print("Too High. Try Again.")
        else:
            print("🏆 You win!")
            gameover = True

game()

Pisst, the secret number is 26
Too low. Try Again.
Too High. Try Again.
🏆 You win!


Write a program to check if a given string is a palindrome (reads the same forwards and backwards).

In [41]:
def is_palindrome(s: str) -> bool:
    i = 0
    j = len(s)-1

    while(i<j):
        if s[i] != s[j]:
            return False
        i += 1
        j -= 1

    return True

is_palindrome("allak")

False

Given a list of numbers, find and print the largest number.

In [50]:
import sys

def get_max(numbers: list[int]) -> int:

    max_num = numbers[0]

    for n in numbers:
        if n > max_num:
            max_num = n
    
    return max_num

scores = [-15, -3, -5, -1, -10]
get_max(scores)

-1

Write a function to reverse a string without using built-in functions like reversed or [::-1]

In [72]:
def reverse_str(s: str) -> str:

    rev = ""
    for i in range(len(s)-1, -1, -1):
        rev = rev + s[i]

    return rev


def reverse_str_v2(s: str):
  rev = ""
  for c in s:
    rev = c + rev
  return rev


reverse_str_v2("mu r at")

'ta r um'

Given a list of numbers, find the second largest number.

In [75]:
scores = [70, 80, 50, 90, 90]

largest = max(scores)
scores.remove(largest)
second_largest = max(scores)

print(second_largest)

90


Given a list of elements, find the element that appears most frequently.

In [81]:
scores = [50, 60, 70, 70, 70, 80, 80, 90]

freq = {}
for s in scores:
    try:
        freq[s] += 1
    except KeyError:
        freq[s] = 1

most_frequent = scores[0]
highest_freq = 0
for s in scores:
    print(freq[s])
    if freq[s] > highest_freq:
        print("found local max", s)
        highest_freq = freq[s]
        most_frequent = s

print(most_frequent)

1
found local max 50
1
3
found local max 70
3
3
2
2
1
70


Find the Longest Word in a Sentence

In [2]:
sentence = "Find the Longest Word in a Sentence"

words = sentence.split()

longest_word = words[0] # Find
for w in words:
    if len(w) > len(longest_word):
        longest_word = w

print(longest_word)

Sentence


Generate 3 random integers that will add up to n

In [37]:
import random

def get_randoms(n):
    r1 = random.randint(1, n-2)
    n2 = n-r1
    r2 = random.randint(1, n2-1)
    r3 = n - r1 - r2
    return (r1, r2, r3)

get_randoms(10)


(3, 2, 5)

Generate Random Password
Create a function to generate a random password of a specified length, including letters, numbers, and special characters

In [40]:
import random

def get_randoms(n):
    r1 = random.randint(1, n-2)
    n2 = n-r1
    r2 = random.randint(1, n2-1)
    r3 = n - r1 - r2
    return (r1, r2, r3)

def password_generator(length):

    letters = ['a', 'b', 'c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
    numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
    specials = ['@', '!', '*', '_', '-', '+']

    letter_cnt, number_cnt, specialchar_cnt = get_randoms(10)
    pwd = ""
    for i in range(letter_cnt):
        pwd += random.choice(letters)

    for i in range(number_cnt):
        pwd += random.choice(numbers)

    for i in range(specialchar_cnt):
        pwd += random.choice(specials)

    return pwd




password_generator(1)

'jiWRj1157@'

Write an extensible converter, which will convert between units of time. ie, hours to seconds, 

In [50]:
class ConversionMachine:
    def __init__(self, converter):
        self.converter = converter

    # delegates the operation to wrapped implementation
    def convert(self, n):
        return self.converter.convert(n)


# concrete implementation of a Converter
class MinToSecConverter:
    def convert(self, val):
        return val * 60
    
# concrete implementation of a Converter
class HourToSecConverter:
    def convert(self, val):
        return val * 60 * 60


converter1 = MinToSecConverter()
converter2 = HourToSecConverter()
cm = ConversionMachine(converter2)
print(cm.convert(1))

3600


FizzBuzz: Write a program that prints numbers from 1 to a given limit.
* For multiples of 3, print "Fizz" instead of the number.
* For multiples of 5, print "Buzz" instead of the number.
* For numbers which are multiples of both 3 and 5, print "FizzBuzz".

In [62]:
def fizzbuzz(limit):

    for i in range(1, limit+1):
        if i % 15 == 0:
            print("FizzBuzz")
        elif i % 3 == 0:
            print("Fizz")
        elif i % 5 == 0:
            print("Buzz")
        else:
            print(i)


fizzbuzz(30)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz


Write a (recursive) program to find n! (factorial is the product of all positive integers less than or equal to n) 

In [63]:
def factorial(n):

    # base case
    if n < 2:
        return 1
    
    # recursive call
    return n * factorial(n-1)

factorial(5)

120

### Fibonacci Sequence
Write a recursive function that calculates the nth Fibonacci number. 

The Fibonacci sequence is defined as follows:

* f(0) = 0
* f(1) = 1
* f(n) = f(n-1) + f(n-2) for n > 1

In [81]:
def fibonacci(n):
    if n < 1:
        return 0
    if n == 1:
        return 1
    
    return fibonacci(n-1) + fibonacci(n-2)


def fibonacci_memoize(n, cache):
    if n < 1:
        return 0
    if n == 1:
        return 1
    
    # check cache first
    cached_result = cache.get(n, 0)
    if cached_result != 0:
        return cached_result

    # cache miss: calculate result and store in cache before returning it
    fib = fibonacci(n-1) + fibonacci(n-2)
    cache[n] = fib

    return fib


fibonacci(44)

# fibonacci_memoize(6, {})

701408733

Reverse an a list (in place), without built-in functions. 

In [88]:
def reverse_inplace(col):
    start = 0
    end = len(col)-1
    while start < end:
        # swap
        col[start], col[end] = col[end], col[start]
        start += 1
        end -= 1

fruits = ["banana", "apple", "orange", "melon"]
print(fruits)

# v1 built in
print(list(reversed(fruits)))

# v2 custom 
reverse_inplace(fruits)
print(fruits)

['banana', 'apple', 'orange', 'melon']
['melon', 'orange', 'apple', 'banana']
['melon', 'orange', 'apple', 'banana']


Weekly sales data for 5 popular phone models across two different stores is stored in two NumPy arrays: 
* Generate random data for 2 stores: store1_sales and store2_sales.
* Calculate the total weekly sales for each phone model
* Find the average weekly sales for each phone model.

In [91]:
import numpy as np

def init_data():
    store1 = np.random.default_rng().integers(low=0, high=100, size=5)
    store2 = np.random.default_rng().integers(low=0, high=100, size=5)

    return store1, store2

store1_sales, store2_sales = init_data()
print(store1_sales)
print(store2_sales)

# total sales
total_sales = store1_sales + store2_sales

# average sales
avg_sales = total_sales / 2

# best seller
max_index = total_sales.argmax()

print(total_sales)
print(avg_sales)
print(max_index, total_sales[max_index])

[48 82 68 58 26]
[19 33 51 55 77]
[ 67 115 119 113 103]
[33.5 57.5 59.5 56.5 51.5]
2 119


Generate 40 random integers representing scores between 20 and 100.
* calculate min, max, range, mean, standard deviation

In [2]:
import numpy as np

scores = np.random.default_rng().integers(low=20, high=100, size=40)

print(type(scores))  # <class 'numpy.ndarray'>
print(scores)
print("Min:", scores.min())
print("Max:", scores.max())
print("Range:", scores.max() - scores.min())
print("Mean:", scores.mean())
print("Std Dev:", scores.std())

<class 'numpy.ndarray'>
[25 97 37 55 28 85 62 36 42 87 80 23 74 31 90 63 70 50 77 36 25 75 85 35
 64 76 92 28 40 94 65 68 39 42 34 39 55 22 99 99]
Min: 22
Max: 99
Range: 77
Mean: 58.1
Std Dev: 24.557890788909376


You have daily stock price data for Apple, Google, and Microsoft. <br>
**Stock price data**
* apple_prices = [100, 105, 102, 108, 110]
* google_prices = [120, 125, 123, 130, 132]
* microsoft_prices = [80, 85, 82, 88, 90]
	
1. Calculate Daily Returns: Calculate the percentage change in price for each stock on a daily basis.

In [106]:
def daily_gains_v1(prices):
    dreturns = [0, 0, 0, 0, 0]
    for i in range(1, len(prices)):
        dreturns[i] = prices[i]-prices[i-1]
    
    return dreturns

def daily_gains_v2(prices):
    np_prices = np.array(prices)
    return (np_prices[1:] - np_prices[:-1])

apple_prices = [100, 105, 102, 108, 110]
google_prices = [120, 125, 123, 130, 132]
microsoft_prices = [80, 85, 82, 88, 90]

print(daily_gains_v1(apple_prices))  # [0, 5, -3, 6, 2]
print(daily_gains_v2(apple_prices))  # [ 5 -3  6  2]

[0, 5, -3, 6, 2]
[ 5 -3  6  2]


Write a Python function is_prime(n) that determines whether a given positive integer n is a prime number.

In [ ]:
import math


def is_prime(n):
    for i in range(2, int(math.sqrt(n))+1):
        if n % i == 0:
            print(f"{n} is NOT prime: divisible by {i}")
            return False

    return True


assert is_prime(4) == False
assert is_prime(9) == False
assert is_prime(7) == True

Implement factorial(n) that calculates the factorial of a non-negative integer n using a loop. 
Hints:
* The factorial of 0 is 1.
* The factorial of n is n multiplied by the factorial of n-1.

In [ ]:
def fact(n):

    if n < 0:
        raise ValueError("Positive numbers only.")
    elif n == 0:
        return 1

    res = 1
    for i in range(1, n+1):
        res *= i

    return res


assert fact(0) == 1
assert fact(1) == 1
assert fact(5) == 120

Write a Python function is_palindrome(s) that determines whether a given string s is a palindrome.
Example:
```python
    is_palindrome("racecar")  # Output: True
    is_palindrome("hello")  # Output: False
```
Hints:
* A palindrome is a word, phrase, number, or other sequence of characters that reads the same backward as forward

In [3]:
def is_palindrome(s):
    left = 0
    right = len(s)-1
    while(left<right):
        if s[left] != s[right]:
            return False
        left += 1
        right -= 1

    return True

assert is_palindrome("racecar") == True
assert is_palindrome("hello") == False