In [74]:
import numpy as np
import torch

torch.__version__

'2.4.1'

In [7]:
# Tensors can be created directly from data. 

# Create a 1-dimensional tensor
tensor1d = torch.tensor([1, 2, 3])

# Create a 2-dimensional tensor
tensor2d = torch.tensor([[1, 2], [3, 4]])


print(tensor1d)
print(tensor2d)

tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])


In [10]:
data = [[1, 2, 3], [4, 5, 6]]
np_array = np.array(data)

# Tensors can be created from NumPy arrays
x_np = torch.from_numpy(np_array)

print(x_np.shape)
print(x_np)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [44]:
tensor = torch.tensor([[0.2],[0.3], [0.4]])
print(tensor.shape)

torch.Size([3, 1])


In [53]:
tensor = torch.ones([2, 4], dtype=torch.float64)

tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [8]:
# creates a 3D tensor with the shape of 2 matrices of 3x4 (3 rows and 4 columns)
tensor = torch.randn(2, 3, 4)
print(tensor.shape)  # torch.Size([2, 3, 4])
print(tensor)

torch.Size([2, 3, 4])
tensor([[[ 0.9161,  0.5751, -1.7719,  0.7283],
         [-1.1367,  0.3688,  1.6488,  0.6709],
         [ 1.1779, -1.3423,  0.1739,  1.5059]],

        [[ 0.8036,  0.1165, -0.0971, -0.2565],
         [ 1.2921, -2.8459, -0.2031, -0.7070],
         [ 0.8128, -0.4673, -0.3811,  0.0535]]])


In [15]:
# 1D tensor filled with zeros
zeros_tensor = torch.zeros(4)   # tensor([0., 0., 0., 0.])

# 2D (2x3) tensor filled with ones
ones_tensor = torch.ones(2, 3)  

print(zeros_tensor)
print(ones_tensor)

tensor([0., 0., 0., 0.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [16]:
# Tensor with values from 0 to 10, stepping by 2
arange_tensor = torch.arange(0, 10, 2)

arange_tensor

tensor([0, 2, 4, 6, 8])

In [17]:
identity_matrix = torch.eye(3)  # 3x3 identity matrix

identity_matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
tensor = torch.rand(3, 4)

print(f"Shape: {tensor.shape}")
print(f"Datatype: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape: torch.Size([3, 4])
Datatype: torch.float32
Device tensor is stored on: cpu


## GPU
* Apple uses a custom-designed GPU architecture.
* Metal Performance Shaders (MPS) is a framework developed by Apple that provides access to the GPU on macOS devices.
* Using MPS means that increased performance can be achieved, by running work on the metal GPU(s). 

In [77]:
# MPS provides GPU acceleration
# Check if the MPS backend is available on your system, and set the device
if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

# Move tensors to the device:
tensor = torch.tensor([1, 2, 3])
tensor = tensor.to(device)

print(tensor)

tensor([1, 2, 3], device='mps:0')


In [30]:
tensor = torch.tensor(
    [[0.0, 0.1, 0.2, 0.3], [1.0, 1.1, 1.2, 1.3], [2.0, 2.1, 2.2, 2.3]])

# Access the element at the first row, second column
element = tensor[0, 1]  # tensor(0.1000)

# v1 First row
r0_v1 = tensor[0]  # tensor([0.0000, 0.1000, 0.2000, 0.3000])

# v2 First row
r0_v2 = tensor[0, :]  # tensor([0.0000, 0.1000, 0.2000, 0.3000])

# Last row
rl = tensor[-1, :]  # tensor([2.0000, 2.1000, 2.2000, 2.3000])

# First column
c0 = tensor[:, 0]  # tensor([0., 1., 2.])

# Last column
cl = tensor[:, -1]  # tensor([0.3000, 1.3000, 2.3000])

r0_v2

tensor([0.0000, 0.1000, 0.2000, 0.3000])

## Operations

In [32]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
scalar = torch.tensor(2)

# Element-wise addition
result = tensor1 + tensor2
print(result)  # Output: tensor([5, 7, 9])

# Element-wise multiplication
result = tensor1 * tensor2
print(result)  # Output: tensor([4, 10, 18])

# Broadcasting
# Scalar 2 is broadcast to match the shape of tensor1
result = tensor1 * scalar
print(result)  # Output: tensor([2, 4, 6])

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([2, 4, 6])


In [33]:
# tensor.T returns the transpose of a tensor
tensor = torch.tensor([[0.0, 0.1, 0.2], [1.0, 1.1, 1.2]])

print(tensor)
print(tensor.T)

tensor([[0.0000, 0.1000, 0.2000],
        [1.0000, 1.1000, 1.2000]])
tensor([[0.0000, 1.0000],
        [0.1000, 1.1000],
        [0.2000, 1.2000]])


In [52]:
# The matrix multiplication between two tensors. 
# use case: grade of a student
scores = torch.tensor([50.0, 60.0, 70.0])
w = torch.tensor([0.2, 0.3, 0.5])

# v1: using @
y1 = scores @ w  # tensor(63.)

# v2: using torch.matmul()
y2 = torch.matmul(scores, w)  # tensor(63.)

tensor3 = torch.tensor([[50.0, 60.0, 70.0], [40.0, 80.0, 80.0]])

y3 = tensor3 @ tensor2

print(y1)
# print(scores.shape)
# print(w.shape)
# print(y1.shape)

tensor(63.)


In [43]:
# The matrix multiplication between two tensors.
prices1 = torch.tensor([100, 200, 300])
prices2 = prices1 * 1.1  # inflation
prices = torch.vstack((prices1, prices2))

qty1 = torch.tensor([10, 20, 30])
qty2 = qty1 * 0.9
qty = torch.vstack((qty1, qty2))

revenue = prices @ qty.T

revenue

tensor([[14000., 12600.],
        [15400., 13860.]])

In [62]:
# Create a sample tensor
tensor = torch.tensor([90, 100, 110], dtype=torch.float32)

# Minimum value
min_value = torch.min(tensor)

# Indice of the minimum
min_index = torch.argmin(tensor)
print("Min value:", min_value, "at index:", min_index)

# Maximum value
max_value = torch.max(tensor)

# Indice of the maximum
max_index = torch.argmax(tensor)
print("Max value:", max_value, "at index:", max_index)

# Mean value
mean_value = torch.mean(tensor)
print("Mean value:", mean_value)

# Median value
median_value = torch.median(tensor)
print("Median value:", median_value)

# Mode value
mode_value = torch.mode(tensor)
print("Mode value:", mode_value)

# Variance
variance = torch.var(tensor)
print("Variance:", variance)

# Standard deviation, sample std by default
std_dev_sample = torch.std(tensor)
print("Sample Standard deviation:", std_dev_sample)

# Standard deviation
std_dev = torch.std(tensor, unbiased=False)
print("Standard deviation:", std_dev)

# Sum
sum_value = torch.sum(tensor)
print("Sum:", sum_value)

Min value: tensor(90.) at index: tensor(0)
Max value: tensor(110.) at index: tensor(2)
Mean value: tensor(100.)
Median value: tensor(100.)
Mode value: torch.return_types.mode(
values=tensor(90.),
indices=tensor(0))
Variance: tensor(100.)
Sample Standard deviation: tensor(10.)
Standard deviation: tensor(8.1650)
Sum: tensor(300.)


## Tensor Views
PyTorch allows a tensor to be a View of an existing tensor. View tensor shares the same underlying data with its base tensor. 

In [73]:
t = torch.zeros(6)

# View tensor shares the same underlying data with its base tensor.
b = t.view(2, 3)

print(t)
print(b)

# Reshape the tensor into a 2x3 matrix
c = torch.reshape(t, shape=(2, 3))

print(c)

# Since c is a view of t, modifying c will also modify t
c[0,0] = 1

print(t)

tensor([0., 0., 0., 0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([1., 0., 0., 0., 0., 0.])


In [85]:
tensor = torch.randn(3, 1)  # torch.Size([3, 1])
print(tensor.shape)
print(tensor)

# Squeeze the singleton dimension
squeezed_tensor = tensor.squeeze()
print(squeezed_tensor.shape)  # torch.Size([3])
print(squeezed_tensor)

torch.Size([3, 1])
tensor([[-2.1039],
        [ 0.7628],
        [ 1.5118]])
torch.Size([3])
tensor([-2.1039,  0.7628,  1.5118])


In [86]:
tensor = torch.randn(1, 3)  # torch.Size([1, 3])
print(tensor.shape)
print(tensor)

# Squeeze the singleton dimension
squeezed_tensor = tensor.squeeze()
print(squeezed_tensor.shape)  # torch.Size([3])
print(squeezed_tensor)

torch.Size([1, 3])
tensor([[ 1.0841, -0.1982, -0.6241]])
torch.Size([3])
tensor([ 1.0841, -0.1982, -0.6241])


In [79]:
tensor = torch.randn(2, 1, 3)  # Shape: (2, 1, 3)
print(tensor.shape)
print(tensor)

# Squeeze the singleton dimension (dimension 1)
squeezed_tensor = tensor.squeeze(1)
print(squeezed_tensor.shape)  # Output: torch.Size([2, 3])
print(squeezed_tensor)

torch.Size([2, 1, 3])
tensor([[[ 0.3827,  0.2891,  0.1187]],

        [[-0.8985,  1.6410,  0.3628]]])
torch.Size([2, 3])
tensor([[ 0.3827,  0.2891,  0.1187],
        [-0.8985,  1.6410,  0.3628]])


In [90]:
tensor = torch.arange(5)
print(tensor.shape)  # torch.Size([5])
print(tensor)  # tensor([0, 1, 2, 3, 4])

# Unsqueeze the singleton dimension
unsqueezed_tensor = tensor.unsqueeze(dim=0)
print(unsqueezed_tensor.shape)  # torch.Size([1, 5])
print(unsqueezed_tensor)  # tensor([[0, 1, 2, 3, 4]])

# Unsqueeze the singleton dimension
unsqueezed_tensor = tensor.unsqueeze(dim=1)
print(unsqueezed_tensor.shape)  # torch.Size([5, 1])
print(unsqueezed_tensor) # tensor([[0],[1],[2],[3],[4]])

torch.Size([5])
tensor([0, 1, 2, 3, 4])
torch.Size([1, 5])
tensor([[0, 1, 2, 3, 4]])
torch.Size([5, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])


In [101]:
# lets assume we know the relationship between x and y
x = torch.arange(10)
y = 2 * x + 1  # tensor([ 3,  5,  7,  9, 11])

print(x)
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])


In [ ]:
import torch.nn as nn