In [9]:
# Linear Search
# Return zero-based index in the list of the first item whose value is equal to x.
# Raises a ValueError if there is no such item.
# Remember, python has a built-in list.index() method, and "in" operator to see if the item is inside the list
def linear_search(x, collection:list):
    for k, v in enumerate(collection):
        if x == v:
            return k
        
    raise ValueError("No such item.")

        
items = ["apple", "orange", "banana", "grapes"]
# q = "watermelon"
q = "orange"

try:
    i = linear_search(q, items)
    print(f"Found {q} at index: {i}")
except ValueError:
    print(f"No such item: {q}")



Found orange at index: 1


In [47]:
#Binary Search
def binary_search(x, col:list):

    begin = 0 # index of the first item
    end = len(col)-1 # index of the last item

    while(begin <= end):

        mid = (begin + end) // 2
        print(f"begin: {begin} end: {end} middle: {mid} compare_to: {col[mid]}")

        # check the value at the middle index, return if found.
        if x == col[mid]:
            return mid
        
        # determine whether to search the left or right half of the list.
        elif(x < col[mid]):
            print("small x. Update 'end' to search the first half only.")
            end = mid - 1
        else:
            print("large x. Update 'begin' search the last half only")
            begin = mid + 1


    
    #return -1
    raise ValueError("No such item.")


# sorted list of items
fruits = ["apple", "banana", "grapes", "mango", "melon", "orange", "watermelon"]
q = "c"

try:
    i = binary_search(q, fruits)
    print(f"Found {q} at index: {i}")
except ValueError:
    print(f"No such item: {q}")

begin: 0 end: 6 middle: 3 compare_to: mango
small x. Update 'end' to search the first half only.
begin: 0 end: 2 middle: 1 compare_to: banana
large x. Update 'begin' search the last half only
begin: 2 end: 2 middle: 2 compare_to: grapes
small x. Update 'end' to search the first half only.
No such item: c


In [57]:
# Binary Search
def binary_search_recursive(x, col: list, begin, end):

    mid = (begin + end) // 2

    print(f"begin: {begin} end: {end} middle: {mid} compare_to: {col[mid]}")
    
    if(begin == end and x != col[mid]):
        raise ValueError("No such item.")

    # check the value at the middle index, return if found.
    if x == col[mid]:
        return mid
    
    # determine whether to search the left or right half of the list.
    if (x < col[mid]):
        print("small x. Update 'end' to search the first half only.")
        end = mid - 1
        return binary_search_recursive(x, col, begin, end)
        

    else:
        print("large x. Update 'begin' search the last half only")
        begin = mid + 1
        return binary_search_recursive(x, col, begin, end)

    # return -1
    



# sorted list of items
fruits = ["apple", "banana", "grapes",
          "mango", "melon", "orange", "watermelon"]
q = "apple"

try:
    i = binary_search_recursive(q, fruits, 0, len(fruits)-1)
    print(f"Found {q} at index: {i}")
except ValueError:
    print(f"No such item: {q}")

begin: 0 end: 6 middle: 3 compare_to: mango
small x. Update 'end' to search the first half only.
begin: 0 end: 2 middle: 1 compare_to: banana
small x. Update 'end' to search the first half only.
begin: 0 end: 0 middle: 0 compare_to: apple
Found apple at index: 0


In [70]:
def arithmetic_grow(n):
    d=1
    s=0
    while(s < n):
        s += d
        print(s)
        # d += 1


# a sequence of numbers that grow at an increasing rate.
# the difference between consecutive terms increases with each iteration
def grow(n):
    dif = 0
    s = 0
    while (s < n):
        s += dif  # s is increasing
        print(s)

        # ensuring that the growth rate increases with each iteration
        dif += 2


grow(10)

0
2
6
12


In [78]:
def factorial(n):

    print(f"factorial({n})")

    # base case
    if n < 0:
        return 0
    elif n < 2:
        print("return 1")
        return 1
    else:
        return n * factorial(n-1)
    
fact = factorial(3)

# assert factorial(0) == 1
# assert factorial(1) == 1
# assert factorial(2) == 2
# assert factorial(3) == 6
# assert factorial(5) == 120

factorial(3)
factorial(2)
factorial(1)
return 1


In [105]:
import math

class Node:
    def __init__(self, data, next=None) -> None:
        self.data = data 
        self.next = next

    def __repr__(self) -> str:
        return f"Node(data={self.data}, next={self.next})"

class LinkedList:
    def __init__(self, head:Node|None=None) -> None:
        self.head = head
        self.length = 1 if head else 0

    def is_empty(self):
        return self.head == None
    
    # prepend (insert at the beginning)
    def add(self, node:Node):
        node.next = self.head
        self.head = node
        self.length += 1
        print("Item added", node.data)

    # pop the first element (at the beginning)
    def pop(self)->Node|None:
        if self.is_empty():
            return None
        
        n = self.head
        self.head = self.head.next
        self.length -= 1
        return n
        

    def contains(self, value):
        if self.is_empty():
            return False
        
        # iterate sequentially
        current = self.head
        while (current):
            if current.data == value:
                return True
            
            current = current.next
        
        return False


# node3 = Node(70)
# node2 = Node(80, next=node3)
# node1 = Node(90, next=node2)
# scores = LinkedList(node1)

# print(scores.head)

fruits = LinkedList()

if fruits.is_empty():
    print("Empty LinkedList")

fruits.add(Node("apple"))
fruits.add(Node("banana"))
fruits.add(Node("mango"))

print(fruits.head)
print("No. of fruits:", fruits.length)

q="banana"
if fruits.contains(q):
    print(f"Item found: {q}")
else:
    print(f"No such element: {q}")

fruit1 = fruits.pop()
print("Popped:", fruit1.data)

fruit2 = fruits.pop()
print("Popped:", fruit2.data)

print("No. of fruits:", fruits.length)

Empty LinkedList
Item added apple
Item added banana
Item added mango
Node(data=mango, next=Node(data=banana, next=Node(data=apple, next=None)))
No. of fruits: 3
Item found: banana
Popped: mango
Popped: banana
No. of fruits: 1


In [8]:
from typing import List 
# import sys

class Node:
    def __init__(self, data, left= None, right= None) -> None:
        self.data = data
        self.left = left
        self.right= right

    def __repr__(self) -> str:
        # return f"Node(data={self.data}, left={self.left}, right={self.right})"
        return f"Node(data={self.data}, left={self.left.data if self.left else None}, right={self.right.data if self.right else None})"

# TODO: incomplete implementation
class BinaryTree:
    def __init__(self, root:Node|None = None) -> None:
        self.root = root

    def add(self, n: Node):
        current = self.root
        while(current):
            if n.data < current.data:
                if not current.left:
                    current.left = n
                    break
                else:
                    current = current.left
            else:
                if not current.right:
                    current.right = n
                    break
                else:
                    current = current.right

    def min(self):
        pass

    def max(self):
        pass

    def prev(self, n: Node):
        pass

    def next(self, n: Node):
        pass


n10 = Node(10)
n20 = Node(20)
n30 = Node(30)
n40 = Node(40)
n50 = Node(50)
n60 = Node(60)
n70 = Node(70)
n80 = Node(80)
n90 = Node(90)

bt = BinaryTree(root=n50)


bt.add(n30)
bt.add(n60)
bt.add(n10)
bt.add(n40)
bt.add(n90)

In [12]:
import math

def traverse_iterative(n: Node) -> List[Node]:
    nodes = []

    # waiting stack
    # all processing will be done popping this stack.
    # which means, the most recent will be the first to be processed.
    frontier = []

    if not n:
        print("Empty tree.")
        return nodes

    frontier.append(n)  # add the first element to waiting stack

    while (frontier):

        # pick the node to be processed
        current = frontier.pop()

        # process
        print("Processing", current)
        nodes.append(current)

        # explore the options: where can i go from here? (children)
        if (current.right):
            frontier.append(current.right)
        if (current.left):
            frontier.append(current.left)

    return nodes


def traverse_recursive(n: Node):

    if not n:
        return []

    left_subtree = traverse_recursive(n.left)
    right_subtree = traverse_recursive(n.right)

    return [n, *left_subtree, *right_subtree]


def sum_recursive(n: Node):

    if not n:
        return 0

    # make 2 recursive calls to calculate the sum of the left and right subtrees.
    left = sum_recursive(n.left)  # sol sulale
    right = sum_recursive(n.right)  # sag sulale

    return n.data + left + right


# Perform a depth-first traversal
# f: Optional function that will be applied to each node during the traversal.
def traverse_recursive_v2(n: Node, f=None):

    print("Debug:", n)
    # return without processing anything
    # effectively stopping the recursion.
    if not n:
        return 0

    # process node
    f(n)

    # Recursive Case: similar subproblem
    traverse_recursive_v2(n.left, f)
    traverse_recursive_v2(n.right, f)


def sum_recursive_v2(n: Node | None, f=None):

    print("Debug:", n)
    # return without processing anything
    # effectively stopping the recursion.
    if not n:
        return 0

    return n.data + sum_recursive_v2(n.left, f) + sum_recursive_v2(n.right, f)


def tree_min(n: Node | None):

    if not n:
        return math.inf

    left_min = tree_min(n.left)
    right_min = tree_min(n.right)

    return min(n.data, left_min, right_min)


# def min(*args):

#     if not args:
#         raise ValueError("No elements to compare")

#     min = args[0]
#     for n in args:
#         if n < min:
#             min = n

    return min


def sum_acc(n, acc):
    return n.data + acc




# print(n80)

# nodes1 = traverse_iterative(n50)
# print(nodes1)

# nodes2 = traverse_recursive(n50)
# print(nodes2)

# traverse_recursive_v2(n50, lambda x: print(x))
# sum = sum_recursive(n50)
# sum = sum_recursive_v2(n50)
# print(sum)

min_data = tree_min(n50);
print(min_data)

10


In [23]:
def single_recursive(n):

    print("processing: ", n)

    # base case
    if n <= 1:
        print("return")
        return 1
    
    # recursive call
    single_recursive(n-1)





def dbl_recursive(n):

    print("processing: ", n)

    # base case
    if n <= 1:
        print("return")
        return 1

    # recursive call
    dbl_recursive(n-1)
    dbl_recursive(n-1)


# single_recursive(5)
dbl_recursive(5)

processing:  5
processing:  4
processing:  3
processing:  2
processing:  1
return
processing:  1
return
processing:  2
processing:  1
return
processing:  1
return
processing:  3
processing:  2
processing:  1
return
processing:  1
return
processing:  2
processing:  1
return
processing:  1
return
processing:  4
processing:  3
processing:  2
processing:  1
return
processing:  1
return
processing:  2
processing:  1
return
processing:  1
return
processing:  3
processing:  2
processing:  1
return
processing:  1
return
processing:  2
processing:  1
return
processing:  1
return


In [27]:
#
amount = 7
coins = [5, 1]

def can_sum(total):

    print("bakiye:", total)

    # base case
    if total < 0:
        return False
    elif total == 0:
        return True

    # recursive case
    res1 = can_sum(total-coins[0])
    res2 = can_sum(total-coins[1])

    return res1 or res2

if(can_sum(amount)):
    print(f"change ok!")
else:
    print(f"change not possible!")

bakiye: 7
bakiye: 2
bakiye: -3
bakiye: 1
bakiye: -4
bakiye: 0
bakiye: 6
bakiye: 1
bakiye: -4
bakiye: 0
bakiye: 5
bakiye: 0
bakiye: 4
bakiye: -1
bakiye: 3
bakiye: -2
bakiye: 2
bakiye: -3
bakiye: 1
bakiye: -4
bakiye: 0
change ok!


In [34]:
def f(n):

   # base case
   # Notice that f(0) returns 1

   if n <= 0:
       return 1

   return n * f(n - 1)
    

def f2(n):
    
    if n <= 1:
        return 1
    
    #two recursive calls            
    return f2(n/2) + f2(n/2)


n = f(-9)
print(n)

1


In [62]:
import torch

x = torch.tensor([10, 20, 30])

print(type(x)) # <class 'torch.Tensor'>
print(x) # tensor([10, 20, 30])

A1 = torch.zeros(2) 
print(A1)

A2 = torch.zeros(3, 2)
print(A2)

A3 = torch.zeros(2, 3, 2)
print(A3)

<class 'torch.Tensor'>
tensor([10, 20, 30])
tensor([0., 0.])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])


In [66]:
import numpy as np

# Create a NumPy array
ndarr = np.array([1, 2, 3, 4, 5])

print(type(ndarr))  # <class 'numpy.ndarray'>
print(ndarr)  #  [1 2 3 4 5]
 # Access the shape attribute (object-oriented)
print(ndarr.shape)  # (5,)

print(ndarr.dtype)  #  int64

A = np.array([[10,20,30],[11,21,31]])
print(A)
print(A.T)

print(A.sum())  # 123
print(np.sum(A))  # 123

<class 'numpy.ndarray'>
[1 2 3 4 5]
(5,)
int64
[[10 20 30]
 [11 21 31]]
[[10 11]
 [20 21]
 [30 31]]
123
123


In [38]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)  #  TensorFlow version: 2.17.0

TensorFlow version: 2.17.0


In [47]:
import tensorflow as tf

x = tf.constant([[1., 2., 3.],[4., 5., 6.]])

print(type(x))  #  <class 'tensorflow.python.framework.ops.EagerTensor'>
print(x)
print(x.shape)  #  (2, 3)
print(x.dtype)  #  <dtype: 'float32'>

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [49]:
import numpy as np

x = np.array([1, 0])
y = np.array([0, 1])

d = x.dot(y)   # 0

d

0

In [53]:
import numpy as np

A = [[10, 20, 30], [11, 21, 31]]
rows = len(A)
cols = len(A[0])
print(f"shape: ({rows}, {cols})") # shape: (2, 3)

A[0][0] = 99
print(A)  # [[99, 20, 30], [11, 21, 31]]

A = np.array([[10, 20, 30],[11, 21, 31]])

print(type(A))  # <class 'numpy.ndarray'>
print(A)
print(A.shape)  # (2, 3)
print(A.dtype)  # int64

shape: (2, 3)
[[99, 20, 30], [11, 21, 31]]
<class 'numpy.ndarray'>
[[10 20 30]
 [11 21 31]]
(2, 3)
int64


In [68]:
import numpy as np

# Create a matrix
A = np.array([[1, 2, 3],
             [4, 5, 6]])

# Calculate the Frobenius norm
frobenius_norm = np.linalg.norm(A, ord='fro')

print(frobenius_norm)  # 9.53939

frobenius_norm2 = np.sqrt(np.sum(A**2))
print(frobenius_norm2)  # 9.53939

9.539392014169456
9.539392014169456


In [73]:
# Create a matrix
A = np.array([[1, 2], [3, 4]])

A_inv = np.linalg.inv(A)

print(A_inv)

print(np.matmul(A, A_inv))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [75]:
import numpy as np

# Define a square matrix
A = np.array([[1, 2],
              [3, 4]])

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [107]:
import numpy as np

data = np.random.default_rng().normal(loc=70,scale=10, size=200)

print(data)

# median
# median = np.median(data)     
q1 = np.percentile(data, 25)  
q2 = np.percentile(data, 50)  
q3 = np.percentile(data, 75)
print(q1, q2, q3)  #   63.23 67.62 74.03

data_q1 = [x for x in data if x<=q1]
print(len(data_q1)) # 10
print(data_q1)

[67.46690292 76.12955063 72.86844336 70.3032818  73.22019731 78.66925856
 71.69202204 63.57154646 64.56725613 84.27682487 58.85065904 62.90143865
 89.09828741 75.86633964 63.77892673 65.41500367 63.15547037 76.43924583
 82.99320072 79.43255668 65.11132102 63.56568815 70.84451473 55.28814903
 68.14070071 93.39621863 41.11936813 83.97685362 67.8379725  76.85200434
 59.67668884 62.98545158 68.68917639 71.95993555 65.32997381 83.0832135
 60.84340611 59.47068346 81.02590143 72.87312852]
63.57008188615148 69.49622909416945 76.54243545530522
10
[58.850659041152426, 62.901438652068435, 63.15547037468338, 63.56568815235347, 55.288149029185064, 41.1193681301717, 59.67668883952358, 62.985451584708656, 60.84340611122187, 59.47068346014509]


In [127]:
import numpy as np

data = np.random.default_rng().normal(loc=70, scale=10, size=200)

print("Population Parameters")
print("Mean:", data.mean())
print("Standart Dev:", data.std())

# Sample 5 elements randomly without replacement
sample = np.random.choice(data, 5, replace=False)
sample2 = np.random.choice(data, 5, replace=False)
# print(sample)

print("Sample Statistics")
print("Means:", sample.mean(), sample2.mean())
print("Standart Devs:", sample.std(ddof=1), sample2.std(ddof=1))

Population Parameters
Mean: 69.01970733979458
Standart Dev: 9.781369680536512
Sample Statistics
Means: 76.47643250258498 73.85952480763548
Standart Devs: 3.9053014618821518 10.446926461453266


In [140]:
ceil = "+ - - - - "
wall = "|         "
ceil_end = "+"
wall_end = "|"

def grid(r:int, c:int):
    for r in range(r):
        for i in range(c):
            print(ceil, end="")
        print(ceil_end)

        for j in range(4):
            for i in range(c):
                print(wall, end="")
            print(wall_end)

    for i in range(c):
        print(ceil, end="")
    print(ceil_end)

grid(3, 2)

+ - - - - + - - - - +
|         |         |
|         |         |
|         |         |
|         |         |
+ - - - - + - - - - +
|         |         |
|         |         |
|         |         |
|         |         |
+ - - - - + - - - - +
|         |         |
|         |         |
|         |         |
|         |         |
+ - - - - + - - - - +


In [142]:
def drawRect(h, w):
    for r in range(h):
        for c in range(w):
            print('#', end="")
        print("")

drawRect(2, 3)

###
###


In [144]:
def multiplication_table(n):
    for i in range(1, 11):
        print(f"{n} * {i} = {n*i}")

multiplication_table(5)

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [151]:
def fact(n):

    if n < 0:
        raise ValueError("Positive numbers only.")
    elif n == 0:
        return 1
    
    res = 1
    for i in range(1, n+1):
        res *= i

    return res

assert fact(0) == 1
assert fact(1) == 1
assert fact(5) == 120

In [174]:
import math

def is_prime(n):
    for i in range(2, int(math.sqrt(n))+1):
        if n % i == 0:
            print(f"{n} is NOT prime: divisible by {i}")
            return False
        
    return True

assert is_prime(4) == False
assert is_prime(9) == False
assert is_prime(7) == True

4 is NOT prime: divisible by 2
9 is NOT prime: divisible by 3


In [199]:
import random

# Generate 3 random numbers that will add up to n.
def three_nums(n):
    a = random.randint(0, n)
    b = random.randint(0, n-a)
    c = n - a - b

    return a,b,c

print(three_nums(10))

(5, 3, 2)


In [203]:
def fizz_buzz(n):

    for i in range(1, n+1):
        if i % 15 == 0:
            print("FizzBuzz")
        elif i %5 == 0:
            print("Buzz")
        elif i%3 == 0:
            print("Fizz")
        else:
            print(i)

fizz_buzz(30)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz


In [209]:
# Write a function that takes a list and returns True if there is any element that appears more than once.

def has_duplicates(col):
    s = set(col)
    return len(s) != len(col)

assert has_duplicates([1, 2,3]) == False
assert has_duplicates([1, 2, 3, 2]) == True
assert has_duplicates([1, "a", 3, "A"]) == False
assert has_duplicates([1, "A", 3, "A"]) == True

In [213]:
# Given a list of elements, find the element that appears most frequently.

def most_freq(col:list):
    freq = {}
    for item in col:
        freq[item] = freq.get(item, 0) + 1

    max_cnt = 0
    max_key = col[0]
    for k in freq:
        if freq[k] > max_cnt:
            max_cnt = freq[k]
            max_key = k

    return max_key


print(most_freq([1, 2, 3, 2, 1, 2, 1, 1]))

1


In [217]:
# Find the Longest Word in a Sentence

def longest_word(sentence: str):
    words = sentence.strip().split(sep=" ")
    
    max_len = 0
    max_word = words[0]
    for w in words:
        wlen = len(w)
        if wlen > max_len:
            max_len = wlen
            max_word = w

    return max_word, max_len

longest_word("Merhaba dunyali biz dostuz!")

('Merhaba', 7)

In [229]:
def is_anagram(s1, s2):
    if len(s1) != len(s2):
        return False
    
    freq1 = {}
    for c in s1:
        freq1[c.lower()] = freq1.get(c.lower(), 0) + 1

    freq2 = {}
    for c in s2:
        freq2[c.lower()] = freq2.get(c.lower(), 0) + 1

    return freq1 == freq2



is_anagram("SilenT", "ListeN")

True

In [231]:
# Reverse an a list (in place), without built-in functions. 

def reverse(col:list):
    left = 0
    right = len(col)-1
    while(left < right):
        col[left], col[right] = col[right], col[left]
        left += 1
        right -= 1

scores = [10, 20, 30, 40, 50]
reverse(scores)
scores

[50, 40, 30, 20, 10]